name: mrx
on:
  push:
  pull_request:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Compile mrx.c
        run: chmod +x *
      - name: Run main.py
        run: python3 main.py
